version: "3.0"
services:
  app:
    image: alexandermrss/nodejs2022q4-service:app
    container_name: app
    build: .
    env_file:
      - .env
    environment:
      PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
    networks:
      - backbone-network
    volumes:
      - type: bind
        source: ./src
        target: /usr/app/src
    restart: always
    depends_on:
      - db
  db:
    image: alexandermrss/nodejs2022q4-service:db
    container_name: ${POSTGRES_HOST}
    build: ./database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - backbone-network
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-log:/var/log/postgresql
    restart: always
volumes:
  db-data:
  db-log:
networks:
  backbone-network:
    driver: bridge